my-yearbook/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from yearbook import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("yearbook.urls")),
    re_path(r'^.*/$', views.error_404, name='error_404'),
]

# Define a custom handler for 404 errors
handler404 = 'yearbook.views.error_404'

yearbook/urls.py
# yearbook/urls.py

from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('', views.home, name='home'), #TODO GALLERY, CLEAN A BIT
    path('remembrancehall/', views.remembrancehall, name='remembrancehall'),
    path('about/', views.about, name='about'),
    path('reminiscencewall/', views.reminiscencewall, name='reminiscencewall'),
    path('students/', views.student_list, name='student_list'), # NEED TO ADD FILTERS
    path('student/new/', views.student_create, name='student_create'),  
    path('student/update/', views.student_update, name='student_update'),
    path('student/<str:student_id>/', views.student_detail, name='student_detail'), # ADD THE IMAGE LATER
    path('student/<int:student_id>/comment/', views.PostCommentView.as_view(), name='post_comment'),
    # path('student/<str:student_id>/delete/', views.student_delete, name='student_delete'),
    path('login/', views.StudentLoginView.as_view(), name='login'), # MAKE IT PRETTIER
    path('logout/', LogoutView.as_view(), name='logout'),
]

yearbook/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.conf import settings


class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)
    color = models.CharField(max_length=7, default='#000000')
    desc = models.CharField(max_length=255, blank=True, null=True)
    
    def __str__(self):
        return self.name
    
class CustomUserManager(BaseUserManager):
    def create_user(self, student_id, email, first_name, last_name, password=None, **extra_fields):
        if not student_id:
            raise ValueError('The Student ID must be set')
        if not email:
            raise ValueError('The Email must be set')
        
        email = self.normalize_email(email)
        user = self.model(student_id=student_id, email=email, first_name=first_name, last_name=last_name, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, student_id, email, first_name, last_name, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        return self.create_user(student_id, email, first_name, last_name, password, **extra_fields)



class Student(AbstractUser):
    username = None  # Remove the username field
    student_id = models.CharField(max_length=7, unique=True, validators=[MinLengthValidator(7)])
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    github_link = models.URLField(blank=True, null=True)
    linkedin_link = models.URLField(blank=True, null=True)
    phone = models.CharField(max_length=12, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    one_liner = models.CharField(max_length=255, blank=True, null=True)
    tags = models.ManyToManyField(Tag, related_name='students', blank=True)


    USERNAME_FIELD = 'student_id'
    REQUIRED_FIELDS = ['email', 'first_name', 'last_name']

    objects = CustomUserManager()

    def __str__(self):
        return self.student_id


class Answer(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name='answers')
    question_number = models.IntegerField()
    answer_text = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"{self.answer_text}"


class Comment(models.Model):
    student = models.ForeignKey(Student, related_name='comments', on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Comment by {self.user} on {self.student}'
    

QUESTIONS = [ "بهترین خاطره (این قسمت برای دیوار خاطره استفاده می شود)؟",
"خنده دار ترین سوتیت چی بود؟",
"اگر به 4 سال پیش برگردی چه کاری رو انجام نمیدی؟\n و چه کاری رو انجام میدی؟",
"چه کاری توی این 4 سال کردی که بهش افتخار میکنی؟",
"انتظار داری 10 سال دیگه کجا باشی؟\n 20 سال دیگه چی؟",
"آخرین حرفت با همدوره ای هات؟",
"توصیف این 4 سال با کلمات پراکنده؟",
"بچه های دورت در جند کلمه؟",
"دوست داری چه شغلی داشته باشی؟",
"فکر میکنی چه درسی رو اگر تو ارائه میدادی بهتر بود؟",
"دوست داشتی چه درسی رو پاس میکردی؟",
"دوست داشتی چه درسی رو پاس نمیکردی؟",
"باحال ترین استاد از نظرت کی بود؟",
"بهترین استاد از نظرت کی بود؟",
"رو مخ ترین پروژه از نظرت کی بود؟",
"پیچوندنی ترین کلاس از نظرت کدوم بود؟",
"اولین دوستت توی دانشگاه کی بود؟",
"بهترین دوستت توی این 4 سال کی بود؟",
"یعقوب یا یعقوب برقی؟",
"اولین چیزی که به ذهنت میاد وقتی میشنوی کورونا؟",
"اولین چیزی که به ذهنت میاد وقتی میشنوی پاتوق؟",
"روز اول دانشگاه؟",
"اولین چیزی که به ذهنت میاد وقتی میشنوی تی ای؟",
"اولین چیزی که به ذهنت میاد وقتی میشنوی سایت؟",
"اولین چیزی که به ذهنت میاد وقتی میشنوی پروژه؟",
"اولین چیزی که به ذهنت میاد وقتی میشنوی انتخاب واحد؟",
"اولین چیزی که به ذهنت میاد وقتی میشنوی طبقه ی اساتید؟",
]

yearbook/forms.py
from django import forms
from django.forms import inlineformset_factory
from django.contrib.auth import get_user_model
from .models import QUESTIONS, Student, Answer, Comment

User = get_user_model()

class StudentRegistrationForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}))
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Repeat Password'}))

    class Meta:
        model = Student
        fields = [
            'student_id', 'first_name', 'last_name', 'email',
            'github_link', 'linkedin_link', 'phone', 'description', 'one_liner'
        ]
        widgets = {
            'student_id': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Student ID'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'First Name'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Last Name'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}),
            'github_link': forms.URLInput(attrs={'class': 'form-control', 'placeholder': 'GitHub Link'}),
            'linkedin_link': forms.URLInput(attrs={'class': 'form-control', 'placeholder': 'LinkedIn Link'}),
            'phone': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Phone'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Description'}),
            'one_liner': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'One Liner'}),
        }

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        student = super().save(commit=False)
        student.set_password(self.cleaned_data["password1"])
        if commit:
            student.save()
        return student

class StudentProfileForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = [
            'github_link', 'linkedin_link', 'phone', 'description', 'one_liner'
        ]
        widgets = {
            'student_id': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Student ID'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'First Name'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Last Name'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}),
            'github_link': forms.URLInput(attrs={'class': 'form-control', 'placeholder': 'GitHub Link'}),
            'linkedin_link': forms.URLInput(attrs={'class': 'form-control', 'placeholder': 'LinkedIn Link'}),
            'phone': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Phone'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Description'}),
            'one_liner': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'One Liner'}),
            'tags': forms.CheckboxSelectMultiple(),
        }


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['question_number', 'answer_text']
        widgets = {
            'question_number': forms.HiddenInput(),
            'answer_text': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Answer text'})
        }
AnswerFormSet = inlineformset_factory(Student, Answer, form=AnswerForm, extra=3)


def get_dynamic_answer_forms(answers=None):
    class DynamicAnswerForm(forms.Form):
        pass

    for i, question in enumerate(QUESTIONS):
        initial_value = answers.get(f'question_{i}') if answers else None
        DynamicAnswerForm.base_fields[f'question_{i}'] = forms.CharField(
            label=question,
            required=False,
            initial=initial_value,
            widget=forms.Textarea(attrs={'class': 'form-control'})
        )

    return DynamicAnswerForm

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        widgets = {
            'text': forms.Textarea(attrs={'class': 'form-control right-align'}),
        }

yearbook/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import View
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate
from django.contrib import messages
from .models import QUESTIONS, Answer, Student
from .forms import CommentForm, StudentProfileForm, AnswerFormSet, get_dynamic_answer_forms
from .forms import StudentRegistrationForm
from django.contrib.auth.views import LoginView

#for messages:
from django.contrib import messages

def home(request):
    return render(request, "yearbook/home.html")

def about(request):
    return render(request, "yearbook/about.html")

def remembrancehall(request):
    students = Student.objects.filter(tags__isnull=False).distinct()
    return render(request, "yearbook/remembrancehall.html",{'students': students})

def reminiscencewall(request):
    answers = Answer.objects.filter(question_number=0)
    return render(request, "yearbook/reminiscencewall.html", {'answers': answers})


def student_list(request):
    students = Student.objects.all()
    return render(request, 'yearbook/student_list.html', {'students': students})

def student_detail(request, student_id):
    student = get_object_or_404(Student, student_id=student_id)
    answers = student.answers.all()  
    comments = student.comments.all()
    questions = QUESTIONS

    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.student = student
            comment.user = request.user
            comment.save()
            messages.success(request, 'کامنت شما اضافه شد')
            return redirect('student_detail', student_id=student_id)
    else:
        comment_form = CommentForm()

    return render(request, 'yearbook/student_detail.html', {
        'student': student,
        'answers': answers,
        'comments': comments,
        'comment_form': comment_form,
        'questions': questions,
        'num_questions': len(questions),
    })


def student_create(request):
    DynamicAnswerForm = get_dynamic_answer_forms()
    if request.method == 'POST':
        student_form = StudentRegistrationForm(request.POST)
        answer_form = DynamicAnswerForm(request.POST)
        if student_form.is_valid() and answer_form.is_valid():
            student = student_form.save()
            for i, question in enumerate(QUESTIONS):
                answer_text = answer_form.cleaned_data.get(f'question_{i}')
                if answer_text:
                    Answer.objects.create(
                        student=student,
                        question_number=i,
                        answer_text=answer_text
                    )
            # Authenticate the user
            student = authenticate(student_id=student.student_id, password=student_form.cleaned_data.get('password1'))
            if student is not None:
                login(request, student)
                messages.success(request, 'ثبت نام با موفقیت انجام شد و شما وارد شدید.')
                return redirect('student_list')
            else:
                messages.error(request, 'مشکلی در ورود به سیستم وجود دارد.')
                return redirect('login')  # Redirect to login page if authentication fails
    else:
        student_form = StudentRegistrationForm()
        answer_form = DynamicAnswerForm()
    
    return render(request, 'yearbook/student_create.html', {
        'student_form': student_form,
        'answer_form': answer_form,
    })


@login_required
def student_update(request):
    DynamicAnswerForm = get_dynamic_answer_forms()  
    student = request.user 

    answers = Answer.objects.filter(student=student)
    answer_dict = {answer.question_number: answer for answer in answers}

    if request.method == 'POST':
        form = StudentProfileForm(request.POST, instance=student)
        if form.is_valid():
            form.save()
            messages.success(request, 'آپدیت شد')

        # Process answer forms for each question
        for i, question in enumerate(QUESTIONS):
            answer_text = request.POST.get(f'question_{i}')
            if answer_text:
                if i in answer_dict:
                    answer = answer_dict[i]
                    answer.answer_text = answer_text
                    answer.save()
                else:
                    Answer.objects.create(
                        student=student,
                        question_number=i,
                        answer_text=answer_text
                    )

        return redirect('student_list')  
    else:
        # Initialize profile form and answer forms
        form = StudentProfileForm(instance=student)
        initial_answers = {f'question_{i}': answer_dict[i].answer_text if i in answer_dict else '' for i, _ in enumerate(QUESTIONS)}
        answer_form = DynamicAnswerForm(initial=initial_answers)

    return render(request, 'yearbook/student_update.html', {
        'form': form,
        'answer_form': answer_form,
    })

@login_required
def student_delete(request, student_id):
    student = get_object_or_404(Student, student_id=student_id)
    if request.method == 'POST':
        student.delete()
        messages.success(request, 'با موفقیت حذف شد')
        return redirect('student_list')
    return render(request, 'yearbook/student_confirm_delete.html', {'student': student})

class StudentLoginView(LoginView):
    template_name = 'yearbook/login.html'


class PostCommentView(LoginRequiredMixin, View):
    def post(self, request, student_id):
        student = get_object_or_404(Student, student_id=student_id)
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.student = student
            comment.user = request.user
            comment.save()
            messages.success(request, 'کامنت شما اضافه شد')
        return redirect('student_detail', student_id=student_id)
    
def error_404(request, exception):
    return render(request, 'yearbook/not_found.html', status=404)

yearbook/templates/yearbook/answer_form.html
<!DOCTYPE html>
<html>
<head>
    <title>New Answer for {{ student.first_name }} {{ student.last_name }}</title>
</head>
<body>
    <h1>New Answer for {{ student.first_name }} {{ student.last_name }}</h1>
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save</button>
    </form>
    <a href="{% url 'student_detail' student.student_id %}">Cancel</a>
</body>
</html>

yearbook/templates/yearbook/student_confirm_delete.html
<!DOCTYPE html>
<html>
<head>
    <title>Delete Student</title>
</head>
<body>
    <h1>Are you sure you want to delete {{ student.first_name }} {{ student.last_name }}?</h1>
    <form action="" method="post">{% csrf_token %}
        <button type="submit">Yes, delete</button>
    </form>
    <a href="{% url 'student_detail' student.student_id %}">Cancel</a>
</body>
</html>

yearbook/templates/yearbook/student_create.html
{% extends 'base.html' %}
{% block title %}Student Form{% endblock %}
{% load static %}
{% load custom_tags %}

{% block extra_css %}
<style>
    .row {
        padding: 60px 30% 60px 30%; 
    }
    .studentform {
        background-color: rgba(23, 38, 79, 0.7); 
        padding: 60px 0; 
    }
    .right-align {
        text-align: right !important;
    }
    .white{
        color: #fff !important; 
    }
    .bottom-padding{
        padding: 0 0 30px 30px; 
    }
    .black {
        color: rgb(0, 0, 0) !important;
    }
    
</style>
{% endblock %}

{% block content %}
    <form method="post" class="studentform">
        {% csrf_token %}
        <div class="row">
            <p class="right-align white"> <strong> در مورد هم دوره ای هاتون خاطره ی بدی رو نگین. اینجا برای خدافظی از همدیگه و ارتباط گرفتن با دوستاتون هست، نه برای بولی کردن همدیگه. کینه هارو کنار بذارین</strong></p>
            <div class="col-12">
                <div class="mb-3 right-align">
                    <label for="id_student_id" class="form-label white">شماره دانشجوبی</label>
                    <input type="text" name="student_id" class="form-control  right-align " id="id_student_id" placeholder="9831023" value="{{ form.student_id.value|default_if_none:'' }}">
                </div>
                <div class="mb-3 right-align">
                    <div class="input-group">
                        <input type="text" name="last_name" class="form-control right-align" id="id_last_name" placeholder="نام خانوادگی" value="{{ form.last_name.value|default_if_none:'' }}">
                        <input type="text" name="first_name" class="form-control right-align" id="id_first_name" placeholder="نام" value="{{ form.first_name.value|default_if_none:'' }}">
                    </div>
                    <label for="id_email" class="form-label white">ایمیل</label>
                    <input type="email" name="email" class="form-control" id="id_email" placeholder="user@gmail.com" value="{{ form.email.value|default_if_none:'' }}">
                </div>
                <div class="mb-3 right-align">
                    <label for="id_github_link" class="form-label white">لینک گیتاب</label>
                    <input type="url" name="github_link" class="form-control" id="id_github_link" placeholder="https://github.com/neginkheirmand" value="{{ form.github_link.value|default_if_none:'' }}">
                </div>
                <div class="mb-3 right-align">
                    <label for="id_linkedin_link" class="form-label white">لینکدین</label>
                    <input type="url" name="linkedin_link" class="form-control" id="id_linkedin_link" placeholder="https://www.linkedin.com/in/neginkheirmand" value="{{ form.linkedin_link.value|default_if_none:'' }}">
                </div>
                <div class="mb-3 right-align">
                    <label for="id_one_liner" class="form-label white">نقل قول</label>
                    <input type="text" name="one_liner" class="form-control right-align " id="id_one_liner" placeholder="همیشه لبخند بزن" value="{{ form.one_liner.value|default_if_none:'' }}">
                </div>
                <div class="mb-3 right-align">
                    <label for="id_phone" class="form-label white">شماره تماس</label>
                    <input type="text" name="phone" class="form-control" id="id_phone" placeholder="09391234567" value="{{ form.phone.value|default_if_none:'' }}">
                </div>
                <div class="mb-3 right-align">
                    <label for="id_description" class="form-label white">دلنامه</label>
                    <textarea name="description" class="form-control right-align" id="id_description" rows="20" placeholder="هرچه میخواهد دل تنگت بنویس">{{ form.description.value|default_if_none:'' }}</textarea>
                </div>
                {% for field in answer_form %}
                    <div class="mb-3 right-align white">
                        <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                        {{ field }}
                    </div>
                {% endfor %}
                <div class="mb-3 right-align ">
                    <label for="id_password1" class="form-label white">پسورد</label>
                    <input type="password" name="password1" class="form-control bottom-padding" id="id_password1" placeholder="Password">
                    <input type="password" name="password2" class="form-control bottom-padding" id="id_password2" placeholder="Repeat Password">
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
    </form>    
{% endblock %}

yearbook/templates/yearbook/student_update.html
{% extends 'base.html' %}
{% block title %}Update Profile{% endblock %}
{% load static %}
{% load custom_tags %}

{% block extra_css %}
<style>
    .row {
        padding: 60px 30% 60px 30%; 
    }
    .studentform {
        background-color: rgba(23, 38, 79, 0.7); 
        padding: 60px 0; 
    }
    .right-align {
        text-align: right !important;
    }
    .white{
        color: #fff !important; 
    }
    .bottom-padding{
        padding: 0 0 30px 30px; 
    }
    .black {
        color: rgb(0, 0, 0) !important;
    }
</style>
{% endblock %}

{% block content %}
    <form method="post" class="studentform">
        {% csrf_token %}
        <div class="row">
            <p class="right-align white"> <strong> در مورد هم دوره ای هاتون خاطره ی بدی رو نگین. اینجا برای خدافظی از همدیگه و ارتباط گرفتن با دوستاتون هست، نه برای بولی کردن همدیگه. کینه هارو کنار بذارین</strong></p>
            <div class="col-12">
                <div class="mb-3 right-align">
                    <label for="id_github_link" class="form-label white">لینک گیتاب</label>
                    <input type="url" name="github_link" class="form-control" id="id_github_link" placeholder="https://github.com/neginkheirmand" value="{{ form.github_link.value|default_if_none:'' }}">
                </div>
                <div class="mb-3 right-align">
                    <label for="id_linkedin_link" class="form-label white">لینکدین</label>
                    <input type="url" name="linkedin_link" class="form-control" id="id_linkedin_link" placeholder="https://www.linkedin.com/in/neginkheirmand" value="{{ form.linkedin_link.value|default_if_none:'' }}">
                </div>
                <div class="mb-3 right-align">
                    <label for="id_one_liner" class="form-label white">نقل قول</label>
                    <input type="text" name="one_liner" class="form-control right-align " id="id_one_liner" placeholder="همیشه لبخند بزن" value="{{ form.one_liner.value|default_if_none:'' }}">
                </div>
                <div class="mb-3 right-align">
                    <label for="id_phone" class="form-label white">شماره تماس</label>
                    <input type="text" name="phone" class="form-control" id="id_phone" placeholder="09391234567" value="{{ form.phone.value|default_if_none:'' }}">
                </div>
                <div class="mb-3 right-align">
                    <label for="id_description" class="form-label white">دلنامه</label>
                    <textarea name="description" class="form-control right-align" id="id_description" rows="20" placeholder="هرچه میخواهد دل تنگت بنویس">{{ form.description.value|default_if_none:'' }}</textarea>
                </div>
                {% for field in answer_form %}
                    <div class="mb-3 right-align white">
                        <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                        {{ field }}
                    </div>
                {% endfor %}
                <button type="submit" class="btn btn-primary">Update</button>
            </div>
        </div>
    </form>    
{% endblock %}